from typing import Union

class Rule:
    def __init__(self, text: str) -> None: ...

    @classmethod
    def is_valid(cls, text: str, _ctx=None) -> bool: ...

    def evaluate(self, thing: dict[str, any] = None, _ctx=None) -> bool: ...

    def matches(self, thing: dict[str, any] = None) -> Union[bool, float, int, str]: ...
